# Generated by Django 4.2.7 on 2023-11-30 07:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Catigories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=20, verbose_name='Название')),
                ('url_cat', models.SlugField(max_length=30)),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Заголовок')),
                ('description', models.TextField(verbose_name='Описание')),
                ('img_small', models.ImageField(upload_to='news/', verbose_name='Изо_маленькое')),
                ('img_middle', models.ImageField(upload_to='news/', verbose_name='Изо_среднее')),
                ('img_large', models.ImageField(upload_to='news/', verbose_name='Изо_большое')),
                ('published', models.DateTimeField(auto_now=True, db_index=True)),
                ('sourсe', models.CharField(max_length=100, verbose_name='Источник')),
                ('url', models.SlugField(max_length=30)),
                ('url_cat', models.SlugField(max_length=30)),
                ('catigory', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='news.catigories', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
            },
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('text', models.TextField(max_length=5000, verbose_name='Message')),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.news', verbose_name='Novost')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='news.reviews', verbose_name='Roditel')),
            ],
            options={
                'verbose_name': 'Otziv',
                'verbose_name_plural': 'OtzivI',
            },
        ),
    ]
