# Generated by Django 4.2.7 on 2023-12-06 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_reviews_options_catigories_published_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catigories',
            name='published',
        ),
        migrations.AddField(
            model_name='reviews',
            name='published',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
    ]
